@APIInjDependencias_HostAddress = http://localhost:5166

GET {{APIInjDependencias_HostAddress}}/singleton/
Accept: application/json

###

GET {{APIInjDependencias_HostAddress}}/scoped/
Accept: application/json

###

GET {{APIInjDependencias_HostAddress}}/transient/
Accept: application/json